LiveApp/urls.py
from django.urls import path
from .views import DetailEventView, CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView, ProfileView, EditProfileView, EditProfilePassView, UpdateEventView

from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'LiveApp'

urlpatterns = [
    path('', views.home, name='home'),

    # registration ; login & logout
    path('signup/', views.registration, name="signup"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),

    # routes to manage events 
    path('events/', views.events_list, name="events_list"),
    path('create/event', views.create_event, name="create_event"),
    path('update/event/<int:id>', UpdateEventView.as_view(), name="update_event"),
    path('delete/event/<int:id>/', views.delete_event, name='delete_event'),

    # route without mixin
    # path('event/<int:id>', views.detail_event, name="detail_event"),
    # route with mixin
    path('event/<int:id>', DetailEventView.as_view(), name='detail_event'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    
    # routes to manage events-users 
    path('add/event/user/<int:id>/', views.add_user_event, name='add_user_event'),
    path('remove/event/user/<int:id>/', views.remove_user_event, name='remove_user_event'),

    # routes to manage auth_user
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile/edit/', EditProfileView.as_view(), name='edit_profile'),
    path('password/edit/', EditProfilePassView.as_view(), name="edit_password" ),

    # routes to reset password 
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tp_EventImmediat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("LiveApp.urls")),
]

LiveApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
# Create your models here.

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()
    place = models.CharField(max_length=100)
    image = models.ImageField(upload_to='event_images/', blank=True, null=True)
    organizer = models.ForeignKey(User, on_delete=models.CASCADE)

class UserEvent(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    registration_date = models.DateTimeField(auto_now_add=True)

LiveApp/forms.py
from django import forms
from .models import Event
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        forms.DateField(widget=forms.DateInput)
        fields = ['title', 'description', 'date', 'place', 'image', 'organizer']
        widgets = {
            'image': forms.ClearableFileInput(),
            'date': forms.DateInput(attrs={'type': 'date'})
        
        }


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

class CustomUserChangeForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].help_text = ''
        self.fields['password'].widget = forms.HiddenInput()
    class Meta:
        model = User
        fields = ['username', 'email']

class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = User

LiveApp/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect

# Modules 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from django.views.generic.edit import FormMixin


from .forms import EventForm, CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm
from .models import Event, UserEvent

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .mixins import UpdateEventMixin
from django.views import View

from django.utils import timezone
from django.core.paginator import Paginator

# Create your views here.

# homepage
def home(request):
    # filter previous events so they're not displayed
    current_date = timezone.now()
    events = Event.objects.filter(date__gte=current_date).order_by('date')[:4]
    latest_users = UserEvent.objects.select_related('user', 'event').filter(event__date__gte=current_date).order_by('-registration_date')[:3]

    return render(request, 'LiveApp/home.html', {'events': events, 'latest_users': latest_users})

# registration
def registration(request): 
    """
    This function allows new user creation. It uses the Django UserCreationForm and the Django login function that allows a user to be logged after its registration."""

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user.save()
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("LiveApp:login")
        else: 
            return render(request, 'LiveApp/registration.html', {"form": form})
    else: 
        form = CustomUserCreationForm()
        return render(request, 'LiveApp/registration.html', {'form': form})

# LogIn
def user_login(request):
    """This function allows the existing user to connect to the website and to redirect it to the homepage with its own informations"""
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("LiveApp:home")
        else: 
            return render(request, 'LiveApp/login.html', {'form': form, 'erreur': "Nom d'utilisateur ou mot de passe incorrect"})
    else:
        form = AuthenticationForm()
        return render(request, 'LiveApp/login.html', {'form': form})

# LogOut
def user_logout(request):
    logout(request)
    return render(request, "LiveApp/logout.html")

# list of all events // already in def home:
def events_list(request):
    current_date = timezone.now()
    # filter previous events so they're not displayed
    events = Event.objects.filter(date__gte=current_date).order_by('date')
    paginator = Paginator(events, 8)

    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, 'LiveApp/list_events.html', {'page': page})

# create an event
def create_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('LiveApp:events_list')
    else:
        form = EventForm()

    return render(request, 'LiveApp/create_event.html', {'form': form})

# see an event with mixin permission if logged 
class DetailEventView(LoginRequiredMixin, View):
    def get(self, request, id):
        event = get_object_or_404(Event, id=id)
        event_user = UserEvent.objects.filter(event=event).order_by('-registration_date')
        user_in_event = UserEvent.objects.filter(event=event, user=request.user).exists()
        return render(request, 'LiveApp/detail_event.html', {'event': event, 'users': event_user, 'user_in_event': user_in_event})


# update an event 
class UpdateEventView(LoginRequiredMixin, UpdateEventMixin, FormMixin, View):
    template_name = 'LiveApp/update_event.html'
    form_class = EventForm

    def get(self, request, *args, **kwargs):
        event = self.get_object()
        form = self.get_form()
        return render(request, self.template_name, {'form': form, 'event': event})

    def post(self, request, *args, **kwargs):
        event = self.get_object()
        form = self.get_form()
        if form.is_valid():
            form.instance = event
            form.save()
            return redirect('LiveApp:detail_event', event.id)
        return render(request, self.template_name, {'form': form, 'event': event})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.get_object()
        return kwargs

    def get_object(self):
        id = self.kwargs.get('id')
        return get_object_or_404(Event, pk=id)

def update_event(request, id):
    event = get_object_or_404(Event, pk=id)
    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return redirect('LiveApp:detail_event', event.id)
    else:
        form = EventForm(instance=event)
    
    return render(request, 'LiveApp/update_event.html', {'form': form, 'event': event})


# delete an event (with javascript - jsonResponse)
def delete_event(request, id):
    event = get_object_or_404(Event, pk=id)
    event.delete()
    return JsonResponse({'message': 'L\'événement a été supprimé avec succès.'})


# subscribe an user to an event
def add_user_event(request, id):
    event = get_object_or_404(Event, id=id)

    if request.method == 'POST':
        user = request.user  # Utilisateur connecté

        # Vérifier si un enregistrement avec le même user_id existe déjà
        if UserEvent.objects.filter(event=event, user=user).exists():
            response_data = {'error': True, 'message': 'Vous êtes déjà inscrit à cet événement.'}
            return JsonResponse(response_data, status=400)

        # Ajouter l'enregistrement si aucun enregistrement existant n'est trouvé
        UserEvent.objects.create(event=event, user=user)
        response_data = {'error': False, 'message': 'Félicitations, votre inscription a bien été prise en compte.'}
        return JsonResponse(response_data, status=200)

    return redirect('LiveApp:detail_event', id=event.id)

# unsubscribe an user to an event 
def remove_user_event(request, id):
    event = get_object_or_404(Event, id=id)
    user = request.user

    try:
        user_event = UserEvent.objects.get(event=event, user=user)
        user_event.delete()
        response_data = {'error': False, 'message': 'Votre désinscription a bien été prise en compte.'}
        return JsonResponse(response_data, status=200)
    except UserEvent.DoesNotExist:
        response_data = {'error': True, 'message': 'Vous n\'êtes pas inscrit à cet événement.'}
        return JsonResponse(response_data, status=400)


# see your profile 

class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        return render(request, 'LiveApp/profile.html', {'user': user})

# Edit profile but only if logged
class EditProfileView(LoginRequiredMixin, View):
    def get(self, request):
        form = CustomUserChangeForm(instance=request.user)
        return render(request, 'LiveApp/edit_profile.html', {'form': form})
    
    def post(self, request):
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('LiveApp:profile')
        else:
            return render(request, 'LiveApp/edit_profile.html', {'form': form})

# edit password but only if logged
class EditProfilePassView(LoginRequiredMixin, View):
    def get(self, request):
        form = PasswordChangeForm(request.user)
        return render(request, 'LiveApp/edit_password.html', {'form': form})
    
    def post(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('LiveApp:profile')
        else:
            return render(request, 'LiveApp/edit_password.html', {'form': form})


# classes to reset password
# view when clicking on "Forgot password ?"
class CustomPasswordResetView(PasswordResetView):
    template_name = 'LiveApp/password_reset.html'
    email_template_name = 'LiveApp/password_reset_email.html'
    success_url = '/password_reset/done/'
    form_class = PasswordResetForm

# view for instructions to check mail
class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'LiveApp/password_reset_done.html'

# view to confirm the reset password (with inputs to change password and confirm it)
class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'LiveApp/password_reset_confirm.html'
    success_url = '/reset/done'

# view to complete the reset of the password with a login url
class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'LiveApp/password_reset_complete.html'

LiveApp/templates/LiveApp/create_event.html
{% extends "LiveApp/base.html" %}
{% block title %}
Event’Immediat | créer un événement
{% endblock %}
{% block content %}
<div class="back">
    <a href="{% url 'LiveApp:events_list' %}">
      <span class="material-symbols-outlined">
          arrow_back
      </span>
  
      Les événements
    </a>
</div>
<form method="post" enctype="multipart/form-data">
    <h2>Créer un événement</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer les modifications</button>
</form>

{% endblock %}

LiveApp/templates/LiveApp/detail_event.html
{% extends "LiveApp/base.html" %}
{% load static %}

{% block title %}
Event’Immediat
{% endblock %}
{% block content %}
<div class="back">
    <a href="{% url 'LiveApp:events_list' %}">
        <span class="material-symbols-outlined">
            arrow_back
        </span>

        Tous les événements
    </a>
    <p>
        {% if user.is_staff or user.is_superuser %}
        <a class="button is-dark is-small" href="{% url "LiveApp:update_event" event.id %}">Modifier l'événement</a>
        <a class="button is-dark is-small delete-event-btn" data-event-id="{{ event.id }}">Supprimer l'événement</a>
        {% endif %}
    </p>
</div>
   <div class="event-hero">
        <div class="event-hero-background" style="background-image: url('{% static 'media/' %}{{ event.image }}')"></div>
        
        <h2>
            {{ event.title }}
            <div>
                le {{ event.date }}
            </div>
        </h2>
    </div>
    <div class="event-content">
        <div class="event-content-text">
            <p class="place">
                <strong><span class="material-symbols-outlined">
                    pin_drop
                </span> {{ event.place }}</strong> 
            </p>
            <p class="organizer">
                Organisateur : <strong>{{ event.organizer }}</strong>
                
            </p>
            <p>
                {{ event.description }}
            </p>
            
        </div>
        <div class="event-content-subscribers">
            {% if user_in_event %}
                <a class="button is-dark is-small" id="desinscription-button" data-event-id="{{ event.id }}">Se désinscrire de l'événement</a>
            {% else %}
                <a class="button is-dark is-small" id="inscription-button" data-event-id="{{ event.id }}">S'inscrire à l'événement</a>
            {% endif %}
            <br/>
            {% if users%}
                {% for user_event in users %}
                    {{ user_event.user.first_name }} {{ user_event.user.last_name }} {% if user.is_staff or user.is_superuser %}- <a href="mailto:{{ user_event.user.email }}">{{ user_event.user.email }}</a>{% endif %}
                {% endfor %}
            {% else %}
                Il n'y a aucun participant à cet événement
            {% endif %}
        </div>
        
    </div>
    

{% endblock %}

LiveApp/templates/LiveApp/edit_password.html
{% extends 'LiveApp/base.html' %}
{% block title %}
Event’Immediat | Changer mon mot de passe
{% endblock %}
{% block content %}
<div class="back">
  <a href="{% url "LiveApp:profile"%}">
    <span class="material-symbols-outlined">
      arrow_back
    </span>

    Retourner au profil
  </a>
</div>
<form method="post">
  <h2>Changer mon mot de passe</h2>
  {% csrf_token %}
  <p>
    {{ form.old_password.label_tag }}: {{ form.old_password }}
  </p>
  <p>
    {{ form.new_password1.label_tag }}: {{ form.new_password1 }}
  </p>
  <p>
    {{ form.new_password2.label_tag }}: {{ form.new_password2 }}
  </p>
  <button type="submit">Enregistrer les modifications</button>
</form>
{% endblock %}

LiveApp/templates/LiveApp/edit_profile.html
{% extends "LiveApp/base.html" %}
{% load static %}

{% block title %}
Event’Immediat | Éditer mon profil
{% endblock %}
{% block content %}
<div class="back">
  <a href="{% url "LiveApp:profile" %}">
    <span class="material-symbols-outlined">
      arrow_back
    </span>

    Retourner au profil
  </a>
</div>
<form method="post">
  <h2>Modifier mon profil</h2>
  {% csrf_token %}
  <p>{{ form.username.label_tag }} {{ form.username }}</p>
  <p>{{ form.email.label_tag }} {{ form.email }}</p>
  <button type="submit">Enregistrer les modifications</button>
</form>
{% endblock %}

LiveApp/templates/LiveApp/error.html
{% extends "LiveApp/base.html" %}
{% block title %}
Event’Immediat | erreur
{% endblock %}
{% block content %}
<div class="form">
    <h2>Erreur</h2>
    <p class="txt_center">Cette page n'existe pas ou son affichage ne vous est pas autorisé.</p>
</div>
{% endblock %}

LiveApp/templates/LiveApp/list_events.html
{% extends "LiveApp/base.html" %}
{% load static %}

{% block title %}
Event’Immediat | Tous nos événements
{% endblock %}
{% block content %}
<div class="back">
  <a href="{% url 'LiveApp:home' %}">
    <span class="material-symbols-outlined">
        arrow_back
    </span>

    Accueil
  </a>

  {% if user.id %}
    <a class="button is-dark is-small" href="{% url "LiveApp:create_event" %}">Créer un événement</a>
  {% endif %}
</div>
  <div class="cards">
  {% for event in page %}
    <div class="card">
      <div class="img-card" style='background-image: url("{% static 'media/' %}{{ event.image }}")'></div>
      <div class="card-content">
        <div class="card-title">
          {{ event.title }}
        </div>
        <div class="card-date">le {{ event.date }}
        </div>
        <div class="card-description">
          {{event.description}}
        </div>
      </div>

      <footer class="card-footer has-background-white-bis">
        <a 
          href="{% url "LiveApp:detail_event" event.id %}" 
          class="card-footer-item p-5 has-text-grey is-uppercase is-text-wide-1">En découvrir plus</a>
      </footer>
    </div>
  
  {% endfor %}
  </div>
  <div class="pagination">
    <div>
      {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Précédent</a>
      {% endif %}
    </div>


    <span class="current-page">Page {{ page.number }}</span>

    <div>
      {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Suivant</a>
      {% endif %}
    </div>

  </div>
  
{% endblock %}

LiveApp/templates/LiveApp/login.html
{% extends "LiveApp/base.html" %}
{% block title %}
Event’Immediat | connexion
{% endblock %}
{% block content %}

<form method="post">
    <h2>Connexion</h2>
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Se connecter</button>

    <p><a href="{% url 'LiveApp:password_reset' %}">Mot de passe oublié ?</a></p>
</form>
{% endblock %}

LiveApp/templates/LiveApp/logout.html
{% extends "LiveApp/base.html" %}
{% block title %}
Event’Immediat | connexion
{% endblock %}
{% block content %}

<div class="form">
    <h2>Vous êtes déconnecté(e).</h2>

    <p class="txt_center">
        <a href="{% url 'LiveApp:home' %}">Retour à l'accueil</a>
    </p>
</div>


{% endblock %}

LiveApp/templates/LiveApp/password_reset.html
{% extends 'LiveApp/base.html' %}
{% block title %}
Event’Immediat | réinitialiser mon mot de passe
{% endblock %}
{% block content %}
  <form method="post">
    <h2>Mot de passe oublié</h2>
    {% csrf_token %}
    <p>
      {{ form.email.label_tag }}
      {{ form.email }}
    </p>
    <button type="submit">Réinitialiser le mot de passe</button>
  </form>
{% endblock %}

LiveApp/templates/LiveApp/password_reset_complete.html
{% extends 'LiveApp/base.html' %}
{% block title %}
Event’Immediat | réinitialiser mon mot de passe
{% endblock %}
{% block content %}
<div class="form">
    <h2>Mot de passe réinitialisé</h2>
    <p class="txt_center">Votre mot de passe a été réinitialisé avec succès.</p>  
    <p class="txt_center"><a href="{% url "LiveApp:login" %}">Page de connexion</a></p>
</div>
{% endblock %}

LiveApp/templates/LiveApp/password_reset_done.html
{% extends 'LiveApp/base.html' %}
{% block title %}
Event’Immediat | réinitialiser mon mot de passe
{% endblock %}
{% block content %}
<div class="form">
    <h2>Réinitialisation du mot de passe</h2>
    <p class="txt_center">Un e-mail contenant les instructions pour réinitialiser votre mot de passe a été envoyé à votre adresse e-mail.</p>  
</div>
{% endblock %}

LiveApp/templates/LiveApp/password_reset_email.html
{% load i18n %}

{% autoescape off %}
Bonjour,

Vous avez demandé la réinitialisation de votre mot de passe. Veuillez suivre le lien ci-dessous pour choisir un nouveau mot de passe :

{{ protocol }}://{{ domain }}{% url 'LiveApp:password_reset_confirm' uidb64=uid token=token %}

Ce lien est valable pendant {{ valid_minutes }} minutes.

Si vous n'avez pas demandé de réinitialisation de mot de passe, veuillez ignorer cet e-mail.

Cordialement,
L'équipe de votre application
{% endautoescape %}

LiveApp/templates/LiveApp/profile.html
{% extends "LiveApp/base.html" %}
{% load static %}

{% block title %}
Event’Immediat | Mon profil
{% endblock %}
{% block content %}
<div class="back">
    <a href="{% url 'LiveApp:home' %}">
      <span class="material-symbols-outlined">
          arrow_back
      </span>
  
      Accueil
    </a>  
    <p class="buttons">
        <a class="button is-dark is-small" href="{% url "LiveApp:edit_profile" %}">Éditer mon profil</a> 
        <a class="button is-dark is-small" href="{% url "LiveApp:edit_password" %}">Changer mon mot de passe</a>
    </p>
  </div>
<div class="form">
    <h2>Mon profil</h2>
    <div class="container"> 
        <img src="{% static 'media/usericon.svg' %}" class="img-user" />
        <span>
            <h3>{{ user.username }}</h3>
            <p class="name"> {{ user.first_name}} {{ user.last_name }}</p>
            <p> {{ user.email }}</p>
            <p> Inscription : <strong>{{ user.date_joined }}</strong></p>
            <p> Dernière connexion : <strong>{{ user.last_login }}</strong></p>
        </span>
    </div>
    
    
</div>
{% endblock %}

LiveApp/templates/LiveApp/update_event.html
{% extends "LiveApp/base.html" %}
{% block title %}
Event’Immediat | modifier un événement
{% endblock %}
{% block content %}
<div class="back">
    <a href="{% url "LiveApp:detail_event" event.id  %}">
      <span class="material-symbols-outlined">
          arrow_back
      </span>
  
      Retourner à l'événement
    </a>
</div>
<form method="post" enctype="multipart/form-data">
    <h2>Modifier l'événement <br/><strong>{{event.title}}</strong></h2>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer</button>
</form>

{% endblock %}